version: '3.9'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile${BUILDER_POSTFIX:-}
#      args:
#        CONFIG: ${CI_BUILD_NAME:-ex}
#    volumes:
#      - ./.env.${CI_BUILD_NAME:-ex}:/app/.env
    ports:
      - '${EXPOSE_PORT:-3000}:3000'
